development:
  adapter: postgresql
  encoding: unicode
  database: dropin_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: dropin_test
  pool: 5
  username:
  password:
